name: bnd-test
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - python=3.10
  - typer
  - pytorch
  - pytorch-cuda=11.8
  - pynwb
  - numpy
  - pandas
  - scipy
  - ndx_pose
  - pip:
      - kilosort
      - -e ./